commerce_ukrposhta.settings:
  type: config_object
  label: 'Ukrposhta settings'
  mapping:
    api_bearer_uuid:
      type: string
      label: 'API Bearer Uuid'
    api_url:
      type: string
      label: 'API request Url'
    language:
      type: string
      label: 'Language'

field.storage_settings.ukrposhta:
  type: mapping
  label: 'Ukrposhta settings'
  mapping:
    max_length:
      type: string
      label: 'Max length'

field.value.ukrposhta:
  type: mapping
  label: 'Ukrposhta'
  mapping:
    city:
      type: string
      label: 'City'
    postoffice:
      type: string
      label: 'Post Office'
